### ISSUE TITLE
Running MTU finder

### ISSUE THREAD

**Issue by hunter-xyz** [MrAminiDev/NetOptix#1]
درود 

برای این گزینه چه عددی باید بزنیم ؟ 

در مورد این توضیح بدید که فلسفه 1 تا 10 رو بدونیم چرا همچین بازه ای هست که نسبت به شرایط عدد مورد نیاز رو انتخاب کنیم 

Enter incremental step (1-10):

**Comment by MrAminiDev** [comment]
سلام خدمت شما ، عدد مشخص شده بین 1 تا 10 فاصله تست هارو بررسی میکنه 

به عنوان مثال 
درصورت وارد کردن عدد 10 فاصله تست ها به صورت 10 تایی میباشد یعنی اول عدد 700 بعد 710 و 720 و 730 را تست میکند اگر بهترین عدد سرور شما 1333 باشد اخرین مقداری که تست میکند 1330 هستش  
اما اگر عدد 1 وارد بکنید فاصله ها 1 عددی میباشد ینی تست اول اگر 700 باید عدد بعدی 701 و 702 و 703 الی اخر را تست میکند تا به نتیجه برسید و اگر عدد سرور شما 1333 باشه دقیقا به همون مقدار 1333 میرسه 

در کل پیشنهاد میشه عددی بین 1 و 2 باشه در این گزینه اما اگر عجله دارید در تنظیم سرور اعداد بالاتر با سرعت بیشتر به نتیجه میرسه

**Comment by hunter-xyz** [comment]
یه عدد الکی زدم تست کردم فهمیدم چیه بعد یادم رفت اینجا بگم ولی هیچ تاثیری نداره روی سرور یه کاره بیهوده اس انگار

میشه بگی روی چی دقیقا تاثیر میزاره ؟

**Comment by MrAminiDev** [comment]
> یه عدد الکی زدم تست کردم فهمیدم چیه بعد یادم رفت اینجا بگم ولی هیچ تاثیری نداره روی سرور یه کاره بیهوده اس انگار
> 
> میشه بگی روی چی دقیقا تاثیر میزاره ؟

کاربرد اصلی تنظیم پکیج ها هستش و از پاکت لاست جلوگیری میکنه
