### ISSUE TITLE
کار نکردن دستورات

### ISSUE THREAD

**Issue by armia84** [MrAminiDev/NetOptix#2]
سلام خسته نباشید
ممنون از زحماتتون

من دوتا مشکل دیدم اول اینکه
بعد از اجرای اسکریپت و انتخاب گزینه 2 (نصب BBR) هیچ اتفاقی نمیوفته و وقتی sysctl net.ipv4.tcp_congestion_control وارد میکنیم جواب میده که cubic هست و bbr فعال نشده
و مشکل دوم این بود که گزینه 3 (حذف BBR و Hybla) هیچ اتفاقی نمیوفته و مثلا اگه Hybla نصب کرده باشیم بعد از وارد کردن sysctl net.ipv4.tcp_congestion_control جواب Hybla میمونه و اینکه وقتی فایل /etc/sysctl.conf رو بعد از انتخاب گزینه 2 یا 3 بررسی میکنم هیچ تغییری اعمال نشده

**Comment by MrAminiDev** [comment]
تشکر از گزاش شما بروز رسانی شد
